name: Context testing
on:  [ push , pull_request ]

jobs:
  functions:

    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
           echo ${{ contains('Hello world', 'llo')}}
           echo ${{ startswith('Hello world', 'he')}}
           echo ${{ endswith('Hello world', 'lo')}}
           echo ${{ format('Hello {0} {1} {2}', 'world', '!', '!')}}

  one:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
